/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package padroesProjetos;

import static org.junit.Assert.assertNotNull;

import org.junit.Test;

public class AppTest {
   @Test
   public void appHasAGreeting() {
      final App classUnderTest = new App();
      assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
   }
}
